apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: mongodb
data:
  mongodb.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
  init.js: |
    db = db.getSiblingDB('nogmet');
    db.createUser({
      user: 'app',
      pwd: 'Oklop123',
      roles: [{ role: 'readWrite', db: 'nogmet' }]
    });
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mongodb
type: Opaque
data:
  username: YXBw
  password: T2tsb3AxMjM=