apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: your-email@example.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx  # Adjust if you are using a different ingress controller
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nogomet-certificate
  namespace: nogomet-virt
spec:
  secretName: nogomet-tls
  dnsNames:
    - nogomet.nik.si
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer