version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_ATLAS_URI=mongodb://mongodb:27017/nogometvirt
      - NODE_ENV=production
      - JWT_SECRET=toleNašeGeslo
      - HTTPS=true
      - REDIS_HOST=redis
    networks:
      - nogomet_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - nogomet_network

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=nogometvirt
    networks:
      - nogomet_network

  redis:
    image: redis
    networks:
      - nogomet_network

networks:
  nogomet_network:
