Vagrant.configure("2") do |config|
    # Choose your desired box and version
    config.vm.box = "ubuntu/mantic64"
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.ssh.forward_agent = true
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  
    config.vm.provision "shell", privileged: true, inline: <<-SHELL
        # Update package lists and install necessary packages
        sudo apt-get update
    
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        ssh -T git@github.com
        git config --global http.sslverify "false"
        git config --global credential.helper store
    
        # Clone the GitHub repository using SSH
        git clone https://github.com/NikPerne/nogomet-virt.git
    
        #install and run nginx
        sudo apt install nginx -y
    
        cd /etc/nginx/sites-available
    
        cat >> /etc/nginx/sites-available/nogomet.config << \EOF
        #The Nginx server instance
        server{
            listen 80;
            server_name nogomet.test.si;
            location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_pass https://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            }
        }
        EOF
    
        sudo cp /etc/nginx/sites-available/nogomet.config /etc/nginx/sites-enabled/
    
        cd /etc/nginx/sites-enabled/
    
        sudo nginx -t
    
        sudo systemctl restart nginx
        # Install nodejs 18
    
        curl -s https://deb.nodesource.com/setup_18.x | sudo bash
    
        sudo apt install nodejs -y
    
        #Start mongoDB
        apt-get install gnupg curl
    
        curl -fsSL https://pgp.mongodb.com/server-7.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-7.0.gpg --dearmor
    
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
      
        apt-get update

        apt-get install -y mongodb-org

        systemctl start mongod

        systemctl enable mongod

        # Change directory to the cloned repository
        cd /home/vagrant/nogomet-virt

        touch .env
        echo 'MONGODB_ATLAS_URI=mongodb+srv://app:Oklop123@vajecluster.t5qjeje.mongodb.net/?retryWrites=true&w=majority\nNODE_ENV=test\nJWT_SECRET=toleNašeGeslo\nHTTPS=false' >> .env

        # Install Node.js dependencies
        npm install

        # Build and run the Angular app
        npm start
    SHELL
end
